/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as CustomerHomeBackupRouteImport } from './routes/customer-home-backup'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as FrontDeskRouteImport } from './routes/front-desk'
import { Route as GuestsRouteImport } from './routes/guests'
import { Route as HousekeepingRouteImport } from './routes/housekeeping'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ServiceBookingsRouteImport } from './routes/service-bookings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as UsersRouteImport } from './routes/users'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as CustomerBookingsRouteImport } from './routes/customer/bookings'
import { Route as CustomerLoginRouteImport } from './routes/customer/login'
import { Route as CustomerOrdersRouteImport } from './routes/customer/orders'
import { Route as CustomerRegisterRouteImport } from './routes/customer/register'
import { Route as CustomerRestaurantRouteImport } from './routes/customer/restaurant'
import { Route as CustomerRoomsRouteImport } from './routes/customer/rooms'
import { Route as CustomerBookRoomIdRouteImport } from './routes/customer/book/$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerHomeBackupRoute = CustomerHomeBackupRouteImport.update({
  id: '/customer-home-backup',
  path: '/customer-home-backup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontDeskRoute = FrontDeskRouteImport.update({
  id: '/front-desk',
  path: '/front-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsRoute = GuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingRoute = HousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceBookingsRoute = ServiceBookingsRouteImport.update({
  id: '/service-bookings',
  path: '/service-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerBookingsRoute = CustomerBookingsRouteImport.update({
  id: '/customer/bookings',
  path: '/customer/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer/login',
  path: '/customer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/customer/orders',
  path: '/customer/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRegisterRoute = CustomerRegisterRouteImport.update({
  id: '/customer/register',
  path: '/customer/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRestaurantRoute = CustomerRestaurantRouteImport.update({
  id: '/customer/restaurant',
  path: '/customer/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoomsRoute = CustomerRoomsRouteImport.update({
  id: '/customer/rooms',
  path: '/customer/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerBookRoomIdRoute = CustomerBookRoomIdRouteImport.update({
  id: '/customer/book/$roomId',
  path: '/customer/book/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit-logs': typeof AuditLogsRoute
  '/branches': typeof BranchesRoute
  '/customer-home-backup': typeof CustomerHomeBackupRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/front-desk': typeof FrontDeskRoute
  '/guests': typeof GuestsRoute
  '/housekeeping': typeof HousekeepingRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/maintenance': typeof MaintenanceRoute
  '/menu': typeof MenuRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/pos': typeof PosRoute
  '/promotions': typeof PromotionsRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/reservations': typeof ReservationsRoute
  '/reviews': typeof ReviewsRoute
  '/rooms': typeof RoomsRoute
  '/service-bookings': typeof ServiceBookingsRoute
  '/services': typeof ServicesRoute
  '/suppliers': typeof SuppliersRoute
  '/tables': typeof TablesRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/register': typeof CustomerRegisterRoute
  '/customer/restaurant': typeof CustomerRestaurantRoute
  '/customer/rooms': typeof CustomerRoomsRoute
  '/customer/': typeof CustomerIndexRoute
  '/customer/book/$roomId': typeof CustomerBookRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit-logs': typeof AuditLogsRoute
  '/branches': typeof BranchesRoute
  '/customer-home-backup': typeof CustomerHomeBackupRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/front-desk': typeof FrontDeskRoute
  '/guests': typeof GuestsRoute
  '/housekeeping': typeof HousekeepingRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/maintenance': typeof MaintenanceRoute
  '/menu': typeof MenuRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/pos': typeof PosRoute
  '/promotions': typeof PromotionsRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/reservations': typeof ReservationsRoute
  '/reviews': typeof ReviewsRoute
  '/rooms': typeof RoomsRoute
  '/service-bookings': typeof ServiceBookingsRoute
  '/services': typeof ServicesRoute
  '/suppliers': typeof SuppliersRoute
  '/tables': typeof TablesRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/register': typeof CustomerRegisterRoute
  '/customer/restaurant': typeof CustomerRestaurantRoute
  '/customer/rooms': typeof CustomerRoomsRoute
  '/customer': typeof CustomerIndexRoute
  '/customer/book/$roomId': typeof CustomerBookRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit-logs': typeof AuditLogsRoute
  '/branches': typeof BranchesRoute
  '/customer-home-backup': typeof CustomerHomeBackupRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/front-desk': typeof FrontDeskRoute
  '/guests': typeof GuestsRoute
  '/housekeeping': typeof HousekeepingRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/maintenance': typeof MaintenanceRoute
  '/menu': typeof MenuRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/pos': typeof PosRoute
  '/promotions': typeof PromotionsRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/reservations': typeof ReservationsRoute
  '/reviews': typeof ReviewsRoute
  '/rooms': typeof RoomsRoute
  '/service-bookings': typeof ServiceBookingsRoute
  '/services': typeof ServicesRoute
  '/suppliers': typeof SuppliersRoute
  '/tables': typeof TablesRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/register': typeof CustomerRegisterRoute
  '/customer/restaurant': typeof CustomerRestaurantRoute
  '/customer/rooms': typeof CustomerRoomsRoute
  '/customer/': typeof CustomerIndexRoute
  '/customer/book/$roomId': typeof CustomerBookRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/audit-logs'
    | '/branches'
    | '/customer-home-backup'
    | '/dashboard'
    | '/documents'
    | '/employees'
    | '/expenses'
    | '/front-desk'
    | '/guests'
    | '/housekeeping'
    | '/inventory'
    | '/invoices'
    | '/kitchen'
    | '/login'
    | '/loyalty'
    | '/maintenance'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/payments'
    | '/pos'
    | '/promotions'
    | '/purchases'
    | '/reports'
    | '/reservations'
    | '/reviews'
    | '/rooms'
    | '/service-bookings'
    | '/services'
    | '/suppliers'
    | '/tables'
    | '/tasks'
    | '/users'
    | '/customer/bookings'
    | '/customer/login'
    | '/customer/orders'
    | '/customer/register'
    | '/customer/restaurant'
    | '/customer/rooms'
    | '/customer/'
    | '/customer/book/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/audit-logs'
    | '/branches'
    | '/customer-home-backup'
    | '/dashboard'
    | '/documents'
    | '/employees'
    | '/expenses'
    | '/front-desk'
    | '/guests'
    | '/housekeeping'
    | '/inventory'
    | '/invoices'
    | '/kitchen'
    | '/login'
    | '/loyalty'
    | '/maintenance'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/payments'
    | '/pos'
    | '/promotions'
    | '/purchases'
    | '/reports'
    | '/reservations'
    | '/reviews'
    | '/rooms'
    | '/service-bookings'
    | '/services'
    | '/suppliers'
    | '/tables'
    | '/tasks'
    | '/users'
    | '/customer/bookings'
    | '/customer/login'
    | '/customer/orders'
    | '/customer/register'
    | '/customer/restaurant'
    | '/customer/rooms'
    | '/customer'
    | '/customer/book/$roomId'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/audit-logs'
    | '/branches'
    | '/customer-home-backup'
    | '/dashboard'
    | '/documents'
    | '/employees'
    | '/expenses'
    | '/front-desk'
    | '/guests'
    | '/housekeeping'
    | '/inventory'
    | '/invoices'
    | '/kitchen'
    | '/login'
    | '/loyalty'
    | '/maintenance'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/payments'
    | '/pos'
    | '/promotions'
    | '/purchases'
    | '/reports'
    | '/reservations'
    | '/reviews'
    | '/rooms'
    | '/service-bookings'
    | '/services'
    | '/suppliers'
    | '/tables'
    | '/tasks'
    | '/users'
    | '/customer/bookings'
    | '/customer/login'
    | '/customer/orders'
    | '/customer/register'
    | '/customer/restaurant'
    | '/customer/rooms'
    | '/customer/'
    | '/customer/book/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  AuditLogsRoute: typeof AuditLogsRoute
  BranchesRoute: typeof BranchesRoute
  CustomerHomeBackupRoute: typeof CustomerHomeBackupRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  EmployeesRoute: typeof EmployeesRoute
  ExpensesRoute: typeof ExpensesRoute
  FrontDeskRoute: typeof FrontDeskRoute
  GuestsRoute: typeof GuestsRoute
  HousekeepingRoute: typeof HousekeepingRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  KitchenRoute: typeof KitchenRoute
  LoginRoute: typeof LoginRoute
  LoyaltyRoute: typeof LoyaltyRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MenuRoute: typeof MenuRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  PaymentsRoute: typeof PaymentsRoute
  PosRoute: typeof PosRoute
  PromotionsRoute: typeof PromotionsRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  ReservationsRoute: typeof ReservationsRoute
  ReviewsRoute: typeof ReviewsRoute
  RoomsRoute: typeof RoomsRoute
  ServiceBookingsRoute: typeof ServiceBookingsRoute
  ServicesRoute: typeof ServicesRoute
  SuppliersRoute: typeof SuppliersRoute
  TablesRoute: typeof TablesRoute
  TasksRoute: typeof TasksRoute
  UsersRoute: typeof UsersRoute
  CustomerBookingsRoute: typeof CustomerBookingsRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  CustomerRegisterRoute: typeof CustomerRegisterRoute
  CustomerRestaurantRoute: typeof CustomerRestaurantRoute
  CustomerRoomsRoute: typeof CustomerRoomsRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerBookRoomIdRoute: typeof CustomerBookRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-home-backup': {
      id: '/customer-home-backup'
      path: '/customer-home-backup'
      fullPath: '/customer-home-backup'
      preLoaderRoute: typeof CustomerHomeBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/front-desk': {
      id: '/front-desk'
      path: '/front-desk'
      fullPath: '/front-desk'
      preLoaderRoute: typeof FrontDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests': {
      id: '/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping': {
      id: '/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof HousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-bookings': {
      id: '/service-bookings'
      path: '/service-bookings'
      fullPath: '/service-bookings'
      preLoaderRoute: typeof ServiceBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/bookings': {
      id: '/customer/bookings'
      path: '/customer/bookings'
      fullPath: '/customer/bookings'
      preLoaderRoute: typeof CustomerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/customer/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders': {
      id: '/customer/orders'
      path: '/customer/orders'
      fullPath: '/customer/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/register': {
      id: '/customer/register'
      path: '/customer/register'
      fullPath: '/customer/register'
      preLoaderRoute: typeof CustomerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/restaurant': {
      id: '/customer/restaurant'
      path: '/customer/restaurant'
      fullPath: '/customer/restaurant'
      preLoaderRoute: typeof CustomerRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/rooms': {
      id: '/customer/rooms'
      path: '/customer/rooms'
      fullPath: '/customer/rooms'
      preLoaderRoute: typeof CustomerRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/book/$roomId': {
      id: '/customer/book/$roomId'
      path: '/customer/book/$roomId'
      fullPath: '/customer/book/$roomId'
      preLoaderRoute: typeof CustomerBookRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  AuditLogsRoute: AuditLogsRoute,
  BranchesRoute: BranchesRoute,
  CustomerHomeBackupRoute: CustomerHomeBackupRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  EmployeesRoute: EmployeesRoute,
  ExpensesRoute: ExpensesRoute,
  FrontDeskRoute: FrontDeskRoute,
  GuestsRoute: GuestsRoute,
  HousekeepingRoute: HousekeepingRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  KitchenRoute: KitchenRoute,
  LoginRoute: LoginRoute,
  LoyaltyRoute: LoyaltyRoute,
  MaintenanceRoute: MaintenanceRoute,
  MenuRoute: MenuRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  PaymentsRoute: PaymentsRoute,
  PosRoute: PosRoute,
  PromotionsRoute: PromotionsRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  ReservationsRoute: ReservationsRoute,
  ReviewsRoute: ReviewsRoute,
  RoomsRoute: RoomsRoute,
  ServiceBookingsRoute: ServiceBookingsRoute,
  ServicesRoute: ServicesRoute,
  SuppliersRoute: SuppliersRoute,
  TablesRoute: TablesRoute,
  TasksRoute: TasksRoute,
  UsersRoute: UsersRoute,
  CustomerBookingsRoute: CustomerBookingsRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerOrdersRoute: CustomerOrdersRoute,
  CustomerRegisterRoute: CustomerRegisterRoute,
  CustomerRestaurantRoute: CustomerRestaurantRoute,
  CustomerRoomsRoute: CustomerRoomsRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerBookRoomIdRoute: CustomerBookRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
